### ISSUE TITLE
Object cancelation doesn't properly recognize and label groups. 

### ISSUE THREAD

**Issue by PhilBaz** [pedrolamas/klipper-preprocessor#12]
### What happened

In Cura......

I have some groups/assemblies. If I want to cancel one ideally it should show as a single 'object' for cancelation, but this doesn't happen. With 4 groups I end up with 7 objects. 

Also, none of the objects takes the name of the group in cura ( i.e. 'group 1'), instead the object names are based on the name of the file ( object_file name_i, object_file name_i+1, object_file name_i+2) , making it even harder to identify what I would like to cancel. 

Finally, the groups all show as overlapping polygons in mainsail making it impossible to identify and cancel the relevant group/object.
### What did you expect to happen

Objects based on grouping, with the object name matching that of the group in the cura object list. 

### How to reproduce

Group a few things, slice and cancel.

### Additional information

Hi Pedro, I know your script only routes to the the cancelation preprocessor. But I thought maybe I should raise the issue with you first. I imagine this is likely an issue that must be fixed with the cancelation preprocessor exe?

**Comment by pedrolamas** [comment]
Hi @PhilBaz, as you very well put, this issue is outside of the control of this script and you will need to raise it directly with the preprocessor cancellation repository.

**Comment by PhilBaz** [comment]
@pedrolamas 

Thanks Pedro. I linked to an issue on the cancleation.exe git. Hopefully they will see it.

**Comment by pedrolamas** [comment]
Following up on our discussion, I am now closing this issue.
