### ISSUE TITLE
Enabling Preprocessor causes 'max_extrude_only_distance' error

### ISSUE THREAD

**Issue by wwian** [pedrolamas/klipper-preprocessor#14]
### What happened

When I use the Klipper Preprossesor, I get an error after print mesh is complete:

Extrude only move too long (-647.247mm vs 500.000mm)
See the 'max_extrude_only_distance' config option for detailsPreprocessor

### What did you expect to happen

The print to start.

### How to reproduce

Enable Klipper Preprossesor in Cura, activating TIMELAPSE_TAKE_FRAME and SET_PRINT_STATS_INFO, slice, then upload to klipper. Start print, run Bed Mesh. After Bed Mesh state has been saved to profile, the error occurs.

### Additional information

![image](https://github.com/pedrolamas/klipper-preprocessor/assets/25714748/4c77aef4-531b-40bc-a736-d763027a569e)
![image](https://github.com/pedrolamas/klipper-preprocessor/assets/25714748/f5be488d-d8fd-4d4c-8248-3bb6811486fc)

**Comment by pedrolamas** [comment]
Hi @wwian, thank you for opening this ticket, however that message is related to your Klipper configuration and not with the klipper-preprocessor plugin.

Please check [here](https://www.klipper3d.org/Slicers.html#large-retraction-settings-may-require-tuning-klipper) for more information on that.
