### ISSUE TITLE
klipper-preprocessor not working with Smart Avionics Cura Master Branch

### ISSUE THREAD

**Issue by PhilBaz** [pedrolamas/klipper-preprocessor#2]
### What happened

The script does not appear to have any effect when used with smart avionics fork of Cura.  I tend to prefer his fork for its rock solid reliability and extra features. 

https://github.com/smartavionics/Cura

### What did you expect to happen

 For the script to work as in Cura 5.2/3.

### How to reproduce

Configure script and slice. 

### Additional information

Ill make a corresponding report at his git.

Thanks Pedro.

**Comment by pedrolamas** [comment]
Can you please upload a sample gcode file sliced on this slicer so I can look and see what is going on?

I'm happy to fix this if it is a simple change that doesn't conflict with mainstream Cura, but I'm not very inclined to support unknown Cura forks as these can diverge a lot from what Cura provides.

**Comment by PhilBaz** [comment]
@pedrolamas 

Fair enough.  Smart Avionics fork is a fairly significant fork. He is a very active developer and very responsive to community feedback with issues. I would imagine his fork is the most actively used of any.  He has developed many features that are excellent, his version is also totally rock solid compared to the UM 5 version.

I've included an Image of the settings and a sliced file.

![gjhgjhg](https://user-images.githubusercontent.com/21558241/221227268-cc989290-a14c-4e3d-90f6-52a43b341129.jpg)
[Untitled test.zip](https://github.com/pedrolamas/klipper-preprocessor/files/10826143/Untitled.test.zip)

**Comment by pedrolamas** [comment]
Well, Layer info comments are definitely on the file, so the problem is something else!

I recommend you take a look at cura.log (Help -> Show Configuration Folder, and search for cura.log) and see if there is any error related to klipper-preprocessor.

Feel free to upload the log if you want me to take a look to!

**Comment by PhilBaz** [comment]
[cura.log.1.zip](https://github.com/pedrolamas/klipper-preprocessor/files/10826263/cura.log.1.zip)

I searched for  ' klipper-preprocessor', but didn't get a hit. I'm not sure what else to look for. I attached the log.

Thanks Pedro.

**Comment by pedrolamas** [comment]
This is the most recent entry on the log for scrips loading:

![image](https://user-images.githubusercontent.com/85504/221232770-19986bae-9d84-4b99-b377-4886c9e1eaf6.png)

There is no indication there that KlipperPreprocessor was loaded (in fact, no reference anywhere on the log when I search for "KlipperPreprocessor")

cura.log.1 is rolled log, you should also have a cura.log which is the one we need here!

**Comment by PhilBaz** [comment]
Ahh. here it is. I just sliced it again and saw the file date update immediately so hopefully something relevant should be in there.
[cura.zip](https://github.com/pedrolamas/klipper-preprocessor/files/10826401/cura.zip)

**Comment by pedrolamas** [comment]
Here it is:

![image](https://user-images.githubusercontent.com/85504/221235087-545d6cee-005b-4d36-9abc-ce16fad161e1.png)

I have no idea where that `%1` bit came from...

**Comment by pedrolamas** [comment]
What did you set for "Path to klipper_estimator"?

**Comment by PhilBaz** [comment]
@pedrolamas 

I put the .exe in the script folder and set the path to it there. Ill just double check, but i think its done properly. Same config in 5.3 worked. Ill check.

.......................

Ahhhh. The path had a typo!!! I'm so sorry Pedro. My fault entirely. I thought I double checked it.

Sorry! Thank you for your help.
