### ISSUE TITLE
klipper-preprocessor does not appear in "add a script" list

### ISSUE THREAD

**Issue by MonkeyMagic77** [pedrolamas/klipper-preprocessor#4]
### What happened

Placed the file in the script folder but get nothing in the add a script list in Cura 5.3.0

### What did you expect to happen

Expected the script to appear in the post processing script list as per instructions.

### How to reproduce

install cura 5.3.0 add KlipperPreprocessor.py to scripts folder.

**Comment by pedrolamas** [comment]
Hi @MonkeyMagic77 what Operating System are you using? What is the full path to the script in your system?

**Comment by MonkeyMagic77** [comment]
Hello, Im using windows 10 and C:\Users\George\AppData\Roaming\cura\5.3\scripts is the default Cura scripts folder.

**Comment by pedrolamas** [comment]
Thanks, that seems correct (the full path should be something like "C:\Users\George\AppData\Roaming\cura\5.3\scripts\KlipperPreprocessor.py" for it to be found by Cura).

On the folder above you will find a "cura.log" can you upload that here please?

**Comment by MonkeyMagic77** [comment]
[cura.log](https://github.com/pedrolamas/klipper-preprocessor/files/11200619/cura.log)

**Comment by pedrolamas** [comment]
I think you might have downloaded the GitHub HTML page of the script, not the script contents!

![image](https://user-images.githubusercontent.com/85504/231183885-6e7ba790-5b39-4e11-8390-a4147d632775.png)

**Comment by MonkeyMagic77** [comment]
Thank you, I copy pasted the contents of the file to a new py file and renamed it and it works.

**Comment by pedrolamas** [comment]
Perfect, given that, I am closing this ticket now!
