### ISSUE TITLE
Not Working for me - Cura 5.2.1

### ISSUE THREAD

**Issue by BigWampa1989** [pedrolamas/klipper-preprocessor#7]
### What happened

I followed your settup steps but it is not adding anything to the GCode not even the Timelapse code. I manually checked and nothing is their. I am pretty new to all this so forgive me if I am making a stupid mistake. Below are the paths I used and screen shots of all the folders and the setup. 

Path to Cancellation: C:\Users\Louis\AppData\Roaming\cura\5.2\Object_Cancellation\preprocess_cancellation-windows.exe

Path to Estimator: C:\Users\Louis\AppData\Roaming\cura\5.2\Klipper_Estimator\klipper_estimator.exe
Moonraker URL: http://XXX.XXX.XX.XXX:7125

Path to Config: /home/LCasadia/printer_data/config/klipper_estimator.json

![Capture](https://github.com/pedrolamas/klipper-preprocessor/assets/124420868/62b24479-31d6-47ae-b3db-97e44456d49e)
![Capture4](https://github.com/pedrolamas/klipper-preprocessor/assets/124420868/1dd98ab4-dc5d-4664-95c9-66b13a95509c)
![Capture3](https://github.com/pedrolamas/klipper-preprocessor/assets/124420868/ba4af2ed-32f5-4119-869c-aa59f8920229)
![Capture2](https://github.com/pedrolamas/klipper-preprocessor/assets/124420868/032677c8-61a4-43f3-b1d1-96525ff13e79)

Moonraker URL: http://XXX.XXX.XX.XXX:7125

Path to Config: /home/LCasadia/printer_data/config/klipper_estimator.json

### What did you expect to happen

See Above

### How to reproduce

See Above

**Comment by pedrolamas** [comment]
Enter the folder `%AppData%\Roaming\cura\5.2`, there should be a `cura.log` there, please check it or upload it here so I can take a look.

**Comment by BigWampa1989** [comment]
[cura.log](https://github.com/pedrolamas/klipper-preprocessor/files/11751820/cura.log)

See attached log. Everything else I did right though? One thing I wasn't sure is if I needed to create the estimator file manually or if it would generate automatically the first time it runs.

**Comment by pedrolamas** [comment]
Ok, so the issue is your "Path to config file", that is a local file path where to store the backup of the config, not a web path!

Try setting it to "C:\Users\Louis\AppData\Roaming\cura\5.2\Klipper_Estimator\klipper_estimator.json" and I believe it should work fine.

**Comment by BigWampa1989** [comment]
So that did fix it. Thank you. However, for some reason running the plugin causes massive delays, not when I slice the file, but when I go to save it to disk or upload it to moonraker. I tried disabling each portion one by one, but even when only Time-lapse is enabled it still causes the massive delay. This delay will eventually load a small model but anything is significance delays for what seems like indefinitely. Even with everything unchecked the delay still exists. Only when I remove it completely from post-processing or break it with the incorrect config path for the estimator does the delay disappear. I have attached the Cura log and a screen shot of what I was trying to upload. I let the fule in the screen shot rub and it took about 20 minutes to load the final upload confirmation. bit sure if this is just due to my laptops limitations or not.

[cura.log](https://github.com/pedrolamas/klipper-preprocessor/files/11784140/cura.log)
![Capture](https://github.com/pedrolamas/klipper-preprocessor/assets/124420868/eed198c4-6226-4d9e-a24c-ca592f301a65)

**Comment by pedrolamas** [comment]
> I let the fule in the screen shot rub and it took about 20 minutes to load the final upload confirmation. bit sure if this is just due to my laptops limitations or not.

What was the size of the gcode file? can you zip it and upload it here?

There's nothing on the log to indicate a single long operation, however klipper_estimator might take a bit of time... not much I can do about that, this is just a script that runs the app.

**Comment by BigWampa1989** [comment]
[cura.log](https://github.com/pedrolamas/klipper-preprocessor/files/11787374/cura.log)
[CE3E3V2_screw_driver8.zip](https://github.com/pedrolamas/klipper-preprocessor/files/11787387/CE3E3V2_screw_driver8.zip)

here is a new log with the actual upload after 20 minutes or so and the gcode file itself

**Comment by pedrolamas** [comment]
I've checked the logs and do see some weird long operations, however these are not related to this script as all it does is run a few apps.

I've just released a new version 1.2.2 of the script that will add more logging so it will enable you to more easily see if any of the external apps called by the script is causing this issue; if it is, I suggest you check with the respective app maintainer.

**Comment by BigWampa1989** [comment]
I downloaded the update and ran it again. The log is attached. I think I put to many of the files in the folder for the estimator and cancel object. My earlier post has a screen shot of what I put in the app folders. Maybe that's why it is slow? Which files are needed for the apps to run on Windows? Sorry for the newb question. Thanks again for your help.

[cura.log](https://github.com/pedrolamas/klipper-preprocessor/files/11801074/cura.log)

**Comment by pedrolamas** [comment]
Can you confirm that you see "Klipper Preprocessor v1.2.2" on the "Post Processing Scripts" window?

The log you attached does not show the added logging I put on 1.2.2, so I believe you probably did some mistake with the update.

**Comment by BigWampa1989** [comment]
I forgot to restart Cura. It updated now. See correct log.

Should i delete any of the files in the App folders for cancel object and estimator?

[cura.log](https://github.com/pedrolamas/klipper-preprocessor/files/11801387/cura.log)

**Comment by pedrolamas** [comment]
Well, I now know that this is not a problem with this script or any of the apps invoked by it!

Here's a partial of the new log entries:

```log
2023-06-20 10:04:07,129 - DEBUG - [MainThread] CuraEngineBackend.CuraEngineBackend._onBackendQuit [969]: Backend finished slicing. Resetting process and socket.
2023-06-20 10:04:09,429 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.KlipperPreprocessor.execute [115]: Initial run...
2023-06-20 10:04:09,640 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.KlipperPreprocessor.execute_preprocess_cancellation [143]: Running preprocess_cancellation...
2023-06-20 10:04:11,637 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.KlipperPreprocessor.execute_klipper_estimator [164]: Running klipper_estimator to get config from Moonraker...
2023-06-20 10:04:11,862 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.KlipperPreprocessor.execute_klipper_estimator [184]: Running klipper_estimator...
2023-06-20 10:04:12,087 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.KlipperPreprocessor.execute [136]: Return output...
2023-06-20 10:04:12,120 - DEBUG - [MainThread] PostProcessingPlugin.PostProcessingPlugin.CreateThumbnail._createSnapshot [15]: Creating thumbnail image...
```

I can see the plugin work started at 10:04:09 and finished by 10:04:12, so a total of 3 seconds!

So whatever you are experiencing, it has to be something else...

Unrelated to this script, but I did notice that "Encoding thumbnail image..." entries seem to take a long time (2 minutes and above) so that might be your best bet to find the problem!

**Comment by BigWampa1989** [comment]
So I figured it out. when the thumbnails are listed after the Klipper script it causes the delay but when the thumbnails are listed before the Klipper script no delay. I attached a log showing both scenarios with the last entry showing them listed first.

[cura.log](https://github.com/pedrolamas/klipper-preprocessor/files/11802195/cura.log)
